# Generated by Django 5.0.2 on 2024-02-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('deficiencia', models.CharField(max_length=300)),
                ('necessidades', models.CharField(max_length=300)),
                ('enderecos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.endereco')),
            ],
        ),
    ]
