# Generated by Django 5.0.2 on 2024-02-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pessoa_deficiencia_alter_pessoa_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='detalhes',
            field=models.CharField(default='Não Fornecido', max_length=300),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='necessidades',
            field=models.CharField(default='Não Fornecida', max_length=300),
        ),
    ]
