# Generated by Django 5.0.2 on 2024-02-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_endereco_bairro_alter_pessoa_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='enderecos',
            new_name='endereco',
        ),
    ]
