# Generated by Django 5.0.2 on 2024-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_enderecos_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='deficiencia',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='base.deficiencia'),
        ),
    ]
