# Generated by Django 5.0.2 on 2024-03-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_deficiencia_remove_pessoa_deficiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='deficiencia',
        ),
        migrations.DeleteModel(
            name='Deficiencia',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia',
            field=models.CharField(default='', max_length=80),
        ),
    ]
