# Generated by Django 5.0.2 on 2024-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_deficiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='deficiencia',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='base.deficiencia'),
        ),
    ]
