# Generated by Django 5.0.2 on 2024-03-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_pessoa_deficiencia_pessoa_deficiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='deficiencia',
            new_name='deficiencias',
        ),
    ]
