# Generated by Django 5.0.2 on 2024-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_deficiencia_pessoa_deficiencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficiencia',
            name='nome',
            field=models.CharField(choices=[('Física', 'Física'), ('Auditiva', 'Auditiva'), ('Psicossocial', 'Psicossocial'), ('Mental', 'Mental'), ('Visual', 'Visual')], default='Não informado', max_length=80),
        ),
    ]
